-- schema v21 → v22
-- ultary_report.status 를 신고요청·삭제조치·거절·보류·정지로 나눈다.
-- MariaDB 10.1. status 가 PENDING/REVIEWING/RESOLVED/REJECTED 일 때 한 문장씩 실행.

ALTER TABLE `ultary_report`
  MODIFY COLUMN `status` ENUM('PENDING','REVIEWING','RESOLVED','REJECTED','REQUESTED','DELETED','ON_HOLD','SUSPENDED') NOT NULL DEFAULT 'PENDING';

UPDATE `ultary_report`
SET `status` = CASE `status`
  WHEN 'PENDING' THEN 'REQUESTED'
  WHEN 'REVIEWING' THEN 'ON_HOLD'
  WHEN 'RESOLVED' THEN 'DELETED'
  WHEN 'REJECTED' THEN 'REJECTED'
  ELSE `status`
END;

ALTER TABLE `ultary_report`
  MODIFY COLUMN `status` ENUM('REQUESTED','DELETED','REJECTED','ON_HOLD','SUSPENDED') NOT NULL DEFAULT 'REQUESTED' COMMENT 'REQUESTED 신고요청, DELETED 삭제조치, REJECTED 거절, ON_HOLD 보류, SUSPENDED 정지';
